### ISSUE TITLE
Change the colour scheme of icons from red to gray across the application

### ISSUE THREAD

**Issue by vibhavsathe** [webaccess/medha-STPC#303]

**Comment by sunainakaul** [comment]
Delete Icon red in color everywhere.
PFA
![DeleteIcon_Color](https://user-images.githubusercontent.com/64400950/80711916-c3dc0200-8b0e-11ea-8b8d-9d6e1b70a71b.jpg)

**Comment by yogesh-dalvi** [comment]
@vibhavsathe do we need the delete icon in red color?

**Comment by yogesh-dalvi** [comment]
Delete icon should be in red color @sunainakaul
