### ISSUE TITLE
Multiple entry display after saving in student login

### ISSUE THREAD

**Issue by minalapte** [webaccess/medha-STPC#348]
Steps:
1. Login with student
2. Go to add education
3. Enter details and click on save with multiple time

Issue: Multiple entry display after saving
Please find screenshot for reference

Note: Check with overall application
![multiple entry display after saving](https://user-images.githubusercontent.com/64399966/80457855-95fb8f80-894d-11ea-9b62-077f974316cf.png)

**Comment by harshvardhan7395** [comment]
fixed the bugs @shreesh1993 .
