### ISSUE TITLE
list of all colleges display in college dropdown at time of student registration

### ISSUE THREAD

**Issue by minalapte** [webaccess/medha-STPC#349]
Steps:
1. Go to student registration form
2. Select state
3. Click on college drop down 
Issue: List of all colleges display

Note: State lable not clarify that it is for student form or state for college selection
Please find screenshot for reference
![list of all colleges display in college dropdown at time of registration](https://user-images.githubusercontent.com/64399966/80458852-1c64a100-894f-11ea-8ce8-31dc4f7c55ab.png)

**Comment by yogesh-dalvi** [comment]
Hey @shreesh1993 can you please look into this issue.

**Comment by harshvardhan7395** [comment]
Hi @yogesh-dalvi list of college feild is independent of state and district and this was resolved with arshul.

**Comment by yogesh-dalvi** [comment]
Okay,  @harshvardhan7395 @shreesh1993  I got it. Can we have some indicator over there that the college does not belong to state and district and that the state and district belong to student's residence? Because of this, our testing team was also quite confused.

**Comment by harshvardhan7395** [comment]
Do you want us to put state and district above address? 
 because there is a divider as it is.
 @yogesh-dalvi @shreesh1993

**Comment by shreesh1993** [comment]
@yogesh-dalvi I think this has been clarified by Arshul/ Devanshu the other day, that is, those fields are part of student address and not the college address.

**Comment by yogesh-dalvi** [comment]
Okay, no problem @shreesh1993

**Comment by shreesh1993** [comment]
We an add section student personal info under that all details related to student will be added and college info where college and stream selection will be there.

**Comment by yogesh-dalvi** [comment]
In the registration page itself @shreesh1993?

**Comment by shreesh1993** [comment]
Yes, I mean its really confusing TBH.

**Comment by yogesh-dalvi** [comment]
Yup sure
