### ISSUE TITLE
District names not being displayed according to selected state for add student in college login

### ISSUE THREAD

**Issue by sunainakaul** [webaccess/medha-STPC#351]
1. Use staging site.
2. Login as college admin.
3. Click on students-->manage students.
4. Select any state and click on district dropdown.
5. All the districts of all the states are displayed.
PFA
![DistrictDisplay_issue](https://user-images.githubusercontent.com/64400950/80460660-c80ef080-8951-11ea-8cb1-258286247e93.jpg)

**Comment by yogesh-dalvi** [comment]
Hey, @shreesh1993  can you please ho through the student registration as we might face this same issue over there also.

**Comment by shreesh1993** [comment]
Yes @yogesh-dalvi I'll look into this and will fix ASAP.

**Comment by shreesh1993** [comment]
@yogesh-dalvi I think this has been already fixed by you guys on development site. Can you please confirm and let me know. For testing purpose I've added **Maharasthra** state with **Pune** district

**Comment by yogesh-dalvi** [comment]
Hey, @shreesh1993 I guess we need to do this in the student registration part also. Below please refer to the screenshot.

![shreesh1](https://user-images.githubusercontent.com/42199573/80946434-ad35f380-8e0b-11ea-970f-868e177cd727.png)

**Comment by shreesh1993** [comment]
Fixed District issue on student registration screen.
