### ISSUE TITLE
Activity issues

### ISSUE THREAD

**Issue by pawan200** [webaccess/medha-STPC#406]
1. Search filter is not the same as with other modules.
2. Activity filter doesn't reset.
3. Date column is not the same.
4. Two loaders in page load.
5. Same icons for 2 different features, i.e. manage activity icon is already used for hire student.
6. Students are allowed to add new activity.

**Comment by harshvardhan7395** [comment]
Icons are same for manage activity batch (In view activity) and view students (In manage events) which should be same since both are showing list of students.
I have checked for but students are not allowed to add new activity. @shreesh1993 @pawan200 .
