### ISSUE TITLE
Not verified students are visible in Add student to event page.

### ISSUE THREAD

**Issue by yogesh-dalvi** [webaccess/medha-STPC#422]
Students not verified by the college should not appear in the Add student to the recruitment/ event drive page. 
`events/:id/college/:id/students`
Above is the API for which changes needs to be done.

**Comment by harshvardhan7395** [comment]
/events/:id/organization/:organizationId/individuals this is the API which needs to be resolved right ?@yogesh-dalvi

**Comment by yogesh-dalvi** [comment]
@harshvardhan7395  go to college admin ->  events -> View Student List -> Add student to recruitment drive

**Comment by harshvardhan7395** [comment]
okay. I will update the API and add the check for verified by the college. I will do the same in adding students to activity batch.
