### ISSUE TITLE
Loading display continuously for manage activity

### ISSUE THREAD

**Issue by minalapte** [webaccess/medha-STPC#632]
1. Login with college admin
2. Do no add student
3. Go to Activity
4. Click on manage activity< add student

Issue: 1.It should validation message if there is no student
2. Loading display continuously
![Loading display continuously for manage activity](https://user-images.githubusercontent.com/64399966/86466911-22616e80-bd52-11ea-8d8f-86bde3d09784.png)

**Comment by shreesh1993** [comment]
This issue was due no student was eligible for activity i.e. empty student array. This issue has been resolved.
