### ISSUE TITLE
Activity nd dae not updated in batch activity

### ISSUE THREAD

**Issue by minalapte** [webaccess/medha-STPC#633]
1. Login with medha admin
2. Create activity with valid dates , names
3. Go to Student login
4. Activity < Manage activity batch< add activity batch
5. Check end date

Issue: Activity nd dae not updated in batch activity

Please find screensshot
![activity end date not updated](https://user-images.githubusercontent.com/64399966/86468015-2abaa900-bd54-11ea-99b0-319bbf6365a7.png)

**Comment by shreesh1993** [comment]
Now activity batch by default will take activity start and end date instead of current date.
