### ISSUE TITLE
Save action gives error page

### ISSUE THREAD

**Issue by minalapte** [webaccess/medha-STPC#669]
1. Login with college admin
2. Go to activity module
3. Click on edit and then save
3. Check page
Issue: Save action gives error page
Please find screens

![Save page gives error page](https://user-images.githubusercontent.com/64399966/87279965-3ace4780-c50f-11ea-908d-9d9f9deb963e.png)

**Comment by shreesh1993** [comment]
College admin cannot edit activity. 
Above screenshot refers to **edit college**. I was not able to replicate this. Tried editing college using college admin, update was successful. @vibhavsathe  @minalapte

**Comment by shreesh1993** [comment]
Tested on staging, issue cannot be replicated. Instead found new bug, when you click edit, and try refresh, it gets redirected to 404 page.
Fixed redirect issue:
Medha admin - Manage college
College admin - View college(College admin don't have rights to access /manage-college page hence it was redirected to 404 page. Now college admin will get redirected to /view-college page instead)
