### ISSUE TITLE
Module redirection page issue after login

### ISSUE THREAD

**Issue by minalapte** [webaccess/medha-STPC#671]
1. Login with credentials(for all login)
2. Clcik on any module
3. Now , logout and again login
4. Check landing page
5. Dashboard is display but not highlighted
Module redirection page issue after login
Please find screenshot
![Module redirection page issue after login](https://user-images.githubusercontent.com/64399966/87282165-9dc0de00-c511-11ea-8dbd-0ceff3ffd383.png)

**Comment by shreesh1993** [comment]
Now when users log default first menu will be selected.
for admins -> dashboard
for students -> profile
