### ISSUE TITLE
alignment of button not proper

### ISSUE THREAD

**Issue by minalapte** [webaccess/medha-STPC#672]
1. Login with credentials(for all login)
2. Check button size

alignment of button not proper

Please find screenshot
![alignment of button not proper](https://user-images.githubusercontent.com/64399966/87282752-335c6d80-c512-11ea-8b93-9c360f077ae0.png)

**Comment by vibhavsathe** [comment]
Can you please clear cache and check once. Seems correct at my end

![image](https://user-images.githubusercontent.com/51232632/87385531-e634d600-c5bb-11ea-9631-75271e8ed4d6.png)

**Comment by shreesh1993** [comment]
Alignment was breaking on extra large screen. Updated and fixed on both College and Event where **Add More** button is present.
