### ISSUE TITLE
save page error for college profile page

### ISSUE THREAD

**Issue by minalapte** [webaccess/medha-STPC#676]
Login with college admin
Go to college profile
![college profile error page](https://user-images.githubusercontent.com/64399966/87431507-5cf5c180-c604-11ea-96f0-f3df79f5adc8.png)

Click on edit and then save
Check page
Issue: Save action gives error page
Please find screens

**Comment by shreesh1993** [comment]
I was not able to replicate this issue instead we found that when you edit and refresh browser then we get 404 page not found error. This has been fixed and pushed already. You can verify and close this issue.
