### ISSUE TITLE
Manage student functionality

### ISSUE THREAD

**Issue by vibhavsathe** [webaccess/medha-STPC#71]
Create the page as per the mock up and implement the functionality

**Comment by vibhavsathe** [comment]
- User name should be Name
- Search and reset functionality doesn't work
- Filter of streams is showing only Civil whereas it should show all the available streams. 
- When we click on delete icon for a student initially observe that u see some different student but just a second later you see the actual student name you want to delete.
- No success/Error message shown on validating a user. Either single/multi-delete.
- If a student is approved then when we hover on the action button for approve/unapprove it shows "approve" whereas it should show as "unapprove" and vice-versa.
- Pagination backend code is also not done. Changing rows per page doesn't reload the page 
- After multi selecting any items of the table and doing any operation i.e verifying/deleting etc the items remain selected and if you delete then the count event doesn't change.

**Comment by yogesh-dalvi** [comment]
While editing student, edit password functionality is pending. Need to make changes in the api itself for the same.
