### ISSUE TITLE
Add multi block and multi delete functionality to maintain consistency

### ISSUE THREAD

**Issue by vibhavsathe** [webaccess/medha-STPC#95]
Add multi block and delete functionality in in all manage screens to maintain consistency through out the application
State,Zone,RPC and College will have these changes

**Comment by yogesh-dalvi** [comment]
Need to enable multi block functionality in college.

**Comment by vibhavsathe** [comment]
Getting error while unblocking - Error unblocking selected colleges

**Comment by vibhavsathe** [comment]
Not able to unblock a single college as well

**Comment by yogesh-dalvi** [comment]
@vibhavsathe , actually no unblock api is present in strapi. The functionality for unblock is done but as the api in strapi is not present you won't be able to unblock any college.
